export const categories = [
  { id: 'bar', name: 'Barra Recheada', icon: 'server' },
  { id: 'sugarplum', name: 'Bombom', icon: 'circle' },
  { id: 'egg', name: 'Ovo de Páscoa', icon: 'droplet' },
  { id: 'panettone', name: 'Panetone', icon: 'octagon' },
  { id: 'gingerbread', name: 'Pão de mel', icon: 'layers' },
];

export const products = [
  {
    id: '1',
    category: {
      id: 'bar', 
      name: 'Barra Recheada', 
      icon: 'server',
    },
    name: 'Amendoim',
    price: 6,
    photo: ''
  },
  {
    id: '2',
    category: {
      id: 'bar', 
      name: 'Barra Recheada', 
      icon: 'server',
    },
    name: 'Brigadeiro',
    price: 6,
    photo: ''
  },
  {
    id: '3',
    category: {
      id: 'sugarplum', 
      name: 'Bombom', 
      icon: 'circle',
    },
    name: 'Côco',
    price: 5,
    photo: ''
  },
];

export const clients = [
  {
    id: '1',
    name: 'Osmair',
    photo: ''
  },
  {
    id: '2',
    name: 'Wanessa',
    photo: ''
  },
  {
    id: '3',
    name: 'Raphael',
    photo: ''
  },
]

export const purchases = [
  {
    id: '1',
    name: 'Barras de Chocolate',
    amount: 5,
    price: 120,
  },
]

export const sales = [
  {
    client: {
      id: '2',
      name: 'Wanessa',
      photo: ''
    },
    product: {
      id: '2',
      category: {
        id: 'bar', 
        name: 'Barra Recheada', 
        icon: 'server',
      },
      name: 'Brigadeiro',
      price: 6,
      photo: ''
    },
    amount: 2,
    price: 12,
    isPaid: false,
  },
  {
    client: {
      id: '2',
      name: 'Wanessa',
      photo: ''
    },
    product: {
      id: '3',
      category: {
        id: 'sugarplum', 
        name: 'Bombom', 
        icon: 'circle',
      },
      name: 'Côco',
      price: 5,
      photo: ''
    },
    amount: 1,
    price: 5,
    isPaid: false,
  },
]

export const stocks = [ 
  {
    id: '1',
    codproduct: '1',
    product: 'Barra Recheada - Amendoim',
    amount: 1,
    hasStock: false,
  },
  {
    id: '2',
    codproduct: '2',
    product: 'Barra Recheada - Brigadeiro',
    amount: 5,
    hasStock: false,
  },
  {
    id: '3',
    codproduct: '3',
    product: 'Bombom - Côco',
    amount: 2,
    hasStock: false,
  },
]

//transactions
export const transactions = [
  {
    id: '',
    description: '',
    modality: 'buy',
    modalityicon: '',
    datetransaction: '01/01/2024',
    amount: 0,
    price: 0,
    ispaid: false,
  }
]

export const highlightTypes = [
  {
    price: '100',
    lastTransaction: '',
  },
]

export const IHightLights = [ 
  {
    buys: {
      price: '100',
      lastTransaction: '',
    },
    sells: {
      price: '50',
      lastTransaction: '',
    },
    total: {
      price: '50',
      lastTransaction: '',
    },
  },
]
export const featherIcons = [
  { name: "link"}, 
  { name: "search"}, 
  { name: "image"}, 
  { name: "menu"}, 
  { name: "radio"}, 
  { name: "minus"}, 
  { name: "plus"}, 
  { name: "info"}, 
  { name: "check"}, 
  { name: "book"}, 
  { name: "pause"}, 
  { name: "frown"}, 
  { name: "mail"}, 
  { name: "home"}, 
  { name: "star"}, 
  { name: "filter"}, 
  { name: "meh"}, 
  { name: "save"}, 
  { name: "user"}, 
  { name: "phone"}, 
  { name: "paperclip"}, 
  { name: "inbox"}, 
  { name: "lock"}, 
  { name: "cloud"}, 
  { name: "eye"}, 
  { name: "camera"}, 
  { name: "delete"}, 
  { name: "heart"}, 
  { name: "chrome"}, 
  { name: "github"}, 
  { name: "upload"}, 
  { name: "download"}, 
  { name: "unlock"}, 
  { name: "play"}, 
  { name: "tag"}, 
  { name: "calendar"}, 
  { name: "database"}, 
  { name: "key"}, 
  { name: "flag"}, 
  { name: "layout"}, 
  { name: "printer"}, 
  { name: "tool"}, 
  { name: "gift"}, 
  { name: "wifi"}, 
  { name: "edit"}, 
  { name: "codepen"}, 
  { name: "gitlab"}, 
  { name: "youtube"}, 
  { name: "twitter"}, 
  { name: "dribbble"}, 
  { name: "instagram"}, 
  { name: "slack"}, 
  { name: "align-left"}, 
  { name: "align-right"}, 
  { name: "archive"}, 
  { name: "arrow-down"}, 
  { name: "arrow-left"}, 
  { name: "arrow-right"}, 
  { name: "arrow-up"}, 
  { name: "battery"}, 
  { name: "bell"}, 
  { name: "bookmark"}, 
  { name: "box"}, 
  { name: "briefcase"}, 
  { name: "chevron-down"}, 
  { name: "chevron-left"}, 
  { name: "chevron-right"}, 
  { name: "chevron-up"}, 
  { name: "circle"}, 
  { name: "clipboard"}, 
  { name: "clock"}, 
  { name: "code"}, 
  { name: "compass"}, 
  { name: "copy"}, 
  { name: "credit-card"}, 
  { name: "crop"}, 
  { name: "facebook"}, 
  { name: "feather"}, 
  { name: "folder"}, 
  { name: "globe"}, 
  { name: "grid"}, 
  { name: "layers"}, 
  { name: "linkedin"}, 
  { name: "list"}, 
  { name: "log-out"}, 
  { name: "map"}, 
  { name: "mic"}, 
  { name: "moon"}, 
  { name: "mouse-pointer"}, 
  { name: "music"}, 
  { name: "pie-chart"}, 
  { name: "rss"}, 
  { name: "scissors"}, 
  { name: "share"}, 
  { name: "shield"}, 
  { name: "shopping-bag"}, 
  { name: "shopping-cart"}, 
  { name: "shuffle"}, 
  { name: "tablet"}, 
  { name: "thermometer"}, 
  { name: "thumbs-down"}, 
  { name: "thumbs-up"}, 
  { name: "trash"}, 
  { name: "tv"}, 
  { name: "users"}, 
  { name: "video"}, 
  { name: "voicemail"}, 
  { name: "external-link"}, 
  { name: "activity"}, 
  { name: "airplay"}, 
  { name: "alert-circle"}, 
  { name: "alert-octagon"}, 
  { name: "alert-triangle"}, 
  { name: "align-center"}, 
  { name: "align-justify"}, 
  { name: "anchor"}, 
  { name: "aperture"}, 
  { name: "arrow-down-circle"}, 
  { name: "arrow-down-left"}, 
  { name: "arrow-down-right"}, 
  { name: "arrow-left-circle"}, 
  { name: "arrow-right-circle"}, 
  { name: "arrow-up-circle"}, 
  { name: "arrow-up-left"}, 
  { name: "arrow-up-right"}, 
  { name: "at-sign"}, 
  { name: "award"}, 
  { name: "bar-chart"}, 
  { name: "bar-chart-2"}, 
  { name: "battery-charging"}, 
  { name: "bell-off"}, 
  { name: "bluetooth"}, 
  { name: "bold"}, 
  { name: "book-open"}, 
  { name: "camera-off"}, 
  { name: "cast"}, 
  { name: "check-circle"}, 
  { name: "check-square"}, 
  { name: "chevrons-down"}, 
  { name: "chevrons-left"}, 
  { name: "chevrons-right"}, 
  { name: "chevrons-up"}, 
  { name: "cloud-drizzle"}, 
  { name: "cloud-lightning"}, 
  { name: "cloud-off"}, 
  { name: "cloud-rain"}, 
  { name: "cloud-snow"}, 
  { name: "codesandbox"}, 
  { name: "coffee"}, 
  { name: "columns"}, 
  { name: "command"}, 
  { name: "corner-down-left"}, 
  { name: "corner-down-right"}, 
  { name: "corner-left-down"}, 
  { name: "corner-left-up"}, 
  { name: "corner-right-down"}, 
  { name: "corner-right-up"}, 
  { name: "corner-up-left"}, 
  { name: "corner-up-right"}, 
  { name: "cpu"}, 
  { name: "crosshair"}, 
  { name: "disc"}, 
  { name: "divide"}, 
  { name: "divide-circle"}, 
  { name: "divide-square"}, 
  { name: "dollar-sign"}, 
  { name: "download-cloud"}, 
  { name: "droplet"}, 
  { name: "edit-2"}, 
  { name: "edit-3"}, 
  { name: "eye-off"}, 
  { name: "fast-forward"}, 
  { name: "figma"}, 
  { name: "file"}, 
  { name: "file-minus"}, 
  { name: "file-plus"}, 
  { name: "file-text"}, 
  { name: "film"}, 
  { name: "folder-minus"}, 
  { name: "folder-plus"}, 
  { name: "framer"}, 
  { name: "git-branch"}, 
  { name: "git-commit"}, 
  { name: "git-merge"}, 
  { name: "git-pull-request"}, 
  { name: "hard-drive"}, 
  { name: "hash"}, 
  { name: "headphones"}, 
  { name: "help-circle"}, 
  { name: "hexagon"}, 
  { name: "italic"}, 
  { name: "life-buoy"}, 
  { name: "link-2"}, 
  { name: "loader"}, 
  { name: "log-in"}, 
  { name: "map-pin"}, 
  { name: "maximize"}, 
  { name: "maximize-2"}, 
  { name: "message-circle"}, 
  { name: "message-square"}, 
  { name: "mic-off"}, 
  { name: "minimize"}, 
  { name: "minimize-2"}, 
  { name: "minus-circle"}, 
  { name: "minus-square"}, 
  { name: "monitor"}, 
  { name: "more-horizontal"}, 
  { name: "more-vertical"}, 
  { name: "move"}, 
  { name: "navigation"}, 
  { name: "navigation-2"}, 
  { name: "octagon"}, 
  { name: "package"}, 
  { name: "pause-circle"}, 
  { name: "pen-tool"}, 
  { name: "percent"}, 
  { name: "phone-call"}, 
  { name: "phone-forwarded"}, 
  { name: "phone-incoming"}, 
  { name: "phone-missed"}, 
  { name: "phone-off"}, 
  { name: "phone-outgoing"}, 
  { name: "play-circle"}, 
  { name: "plus-circle"}, 
  { name: "plus-square"}, 
  { name: "pocket"}, 
  { name: "power"}, 
  { name: "refresh-ccw"}, 
  { name: "refresh-cw"}, 
  { name: "repeat"}, 
  { name: "rewind"}, 
  { name: "rotate-ccw"}, 
  { name: "rotate-cw"}, 
  { name: "send"}, 
  { name: "server"}, 
  { name: "settings"}, 
  { name: "share-2"}, 
  { name: "shield-off"}, 
  { name: "sidebar"}, 
  { name: "skip-back"}, 
  { name: "skip-forward"}, 
  { name: "slash"}, 
  { name: "sliders"}, 
  { name: "smartphone"}, 
  { name: "smile"}, 
  { name: "speaker"}, 
  { name: "square"}, 
  { name: "stop-circle"}, 
  { name: "sun"}, 
  { name: "sunrise"}, 
  { name: "sunset"}, 
  { name: "target"}, 
  { name: "terminal"}, 
  { name: "toggle-left"}, 
  { name: "toggle-right"}, 
  { name: "trash-2"}, 
  { name: "trello"}, 
  { name: "trending-down"}, 
  { name: "trending-up"}, 
  { name: "triangle"}, 
  { name: "truck"}, 
  { name: "twitch"}, 
  { name: "type"}, 
  { name: "umbrella"}, 
  { name: "underline"}, 
  { name: "upload-cloud"}, 
  { name: "user-check"}, 
  { name: "user-minus"}, 
  { name: "user-plus"}, 
  { name: "user-x"}, 
  { name: "video-off"}, 
  { name: "volume"}, 
  { name: "volume-1"}, 
  { name: "volume-2"}, 
  { name: "volume-x"}, 
  { name: "watch"}, 
  { name: "wifi-off"}, 
  { name: "wind"}, 
  { name: "x"}, 
  { name: "x-circle"}, 
  { name: "x-octagon"}, 
  { name: "x-square"}, 
  { name: "zap"}, 
  { name: "zap-off"}, 
  { name: "zoom-in"}, 
  { name: "zoom-out"}
]
